config/routes.rb
Rails.application.routes.draw do
  resources :sparks

end

app/models/light.rb
class Light
  include ActiveModel::Model

  attr_accessor :name, :device_id, :token

  def color
    api.query('color')['result']
  end

  def update(status)
    api.command(status)
  end

  def api
    @api ||= Spark.new(device_id, token)
  end
end

app/models/spark.rb
require 'net/http'

class Spark
  attr_reader :message

  def initialize(device, token)
    @device = device
    @token = token
  end

  def command(command)
    response = Net::HTTP.post_form(uri(command), {"access_token" => token})
    @message = response.message
    response.code == "200"
  end

  def query(query)
    response = Net::HTTP.get_response uri(query + "?access_token=#{token}")
    ActiveSupport::JSON.decode response.body
  end

  private

  attr_reader :token, :device

  def uri(command_or_query)
    path = "v1/devices/#{device}/#{command_or_query}"
    URI.parse("https://api.particle.io/#{path}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sparks_controller.rb
class SparksController < ApplicationController
  before_action :setup_devices

  def index
  end

  def update
    @light = @lights.find { |light| light.device_id == params[:id] }
    if @light.update(params[:status])
      redirect_to sparks_path, notice: "#{@light.name} changed to #{params[:status]}"
    else
      flash.now[:error] = @light.api.message
      render 'index'
    end
  end

  private

  def setup_devices
    @lights = [
      Light.new(name: 'Abby', device_id: ENV['ABBY'], token: ENV['SPARK_TOKEN']),
      Light.new(name: 'Emma', device_id: ENV['EMMA'], token: ENV['SPARK_TOKEN'])
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sparks_helper.rb
module SparksHelper
  def time_format(time)
    time = Time.parse time
    time.in_time_zone.strftime("%m/%d/%Y %l:%M:%S %p")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clock</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>

<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/lights/_light.html.erb
<div class="sparks show">
  <h3><%= light.name %></h3>
  Color: <span class="color <%= light.color %>"></span><br/>
  <br/>
  <%= form_tag spark_path(light.device_id), method: :patch do %>
    <%= hidden_field_tag :status, 'wakeUp' %>
    <%= submit_tag 'Wake Up', class: 'btn btn-large' %>
  <% end %>

  <%= form_tag spark_path(light.device_id), method: :patch do %>
    <%= hidden_field_tag :status, 'sleep' %>
    <%= submit_tag 'Sleep', class: 'btn btn-large' %>
  <% end %>
</div>

app/views/sparks/index.html.erb
<%= render @lights %>